name: shellstone
version: 0.1.0
homepage: https://github.com/lessonteacher/shellstone
authors:
- Hugo Armstrong <@lessonteacher>
description:
  An attempt at producing a Redstone / Shelf based package to also do some ORM
  functionality

dev_dependencies:
  test: '^0.12.0'
  grinder: "^0.8.0+2"
